apiVersion: apps/v1
kind: Deployment
metadata:
  name: service6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service6
  template:
    metadata:
      labels:
        app: service6
    spec:
      containers:
      - name: service6
        image: umapathy22/service6
        ports:
        - containerPort: 3006
        env:
        - name: PORT
          value: "3006"
---
apiVersion: v1
kind: Service
metadata:
  name: service6
spec:
  selector:
    app: service6
  ports:
  - port: 3006
    targetPort: 3006
  type: LoadBalancer
